# Default values for rust-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: jabdoa/mpf-crash-reporter
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  name: mpf-crash-reporter
  type: LoadBalancer
  externalPort: 8080
  internalPort: 8080

resources:
  limits:
    cpu: 1
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

ingress:
  enabled: true
  hosts:
    - crashes.missionpinball.org
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: mpf-crash-reporter-tls
      hosts:
        - crashes.missionpinball.org

persistence:
  accessMode: ReadWriteOnce
  size: 20Gi
