[package]
name = "mpf-crash-reporter"
version = "0.1.0"
authors = ["Jan Kantert <jan-mpf@kantert.net>"]
edition = "2018"

[dependencies]
actix-web = "3"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.8"
uuid = { version = "0.8", features = ["v4"] }
serde_json = "1.0"